### PR TITLE
Check existence of -p argument correctly for clang-tidy and oclint

### LINKED ISSUE #15: "-p" checking for oclint/clang-tidy always fails
if "-p" is specified alone (so the "-p" in args -check could succeed) clang-tidy complains about missing value.

If it's specified correctly for clang-tidy ("-p=cmake-build-debug") then the check fails and the -D is added which makes clang-tidy not find for example included libraries...

I will submit a PR soonish.

### PR DESCRIPTION
**Pull request by rambo**
Fixes #15

### CODE REVIEW

**Comment by pocc** [comment]
I appreciate the PR and it does fix this issue. I'm just wondering about the best way to go about this. I would just like to flat-out delete the lines causing this issue because they're not necessary in the first place. The `add_if_missing` for `-- -DCMAKE_EXPORT_OPTIONS` suppresses an error,  but on reflection is not necessary, and causes the problem you experienced. If you deleted these lines in your PR instead, I would merge.

What do you think?

**Comment by rambo** [comment]
I would probably have made a separate issue about removing the flag completely, but this works too.

**Comment by rambo** [comment]
That build failure is "interesting", I'd say we revert to the working commit 04df1e0 and you look at removing the cmake flag in the future...

**Comment by pocc** [comment]
Yeah it's complaining about the lack of a compilation database, which is now not suppressed. It shouldn't be too hard to dynamically generate a compilation database per test.

**Comment by pocc** [comment]
Would you mind squashing the commits to just the [tests file](https://github.com/pocc/pre-commit-hooks/pull/16/files#diff-d2636131c96b9efb0082fd9ffceb8b8c)? I think the tests are useful and I'll the cmake changes sometime today.

**Comment by rambo** [comment]
Squashed the test together with the fix now.

For future reference: The test for checking that the cmake flag is removed is at https://github.com/pocc/pre-commit-hooks/blob/5637a042c5dbef919c296d93004b6426f35e082d/tests/test_dashp.py

**Comment by pocc** [comment]
Thanks for making this!

**Pull request merged**
